const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const embedded=new URLSearchParams(location.search).has('frame_id');
const prefix=embedded?'/.proxy':'';const url=p=>prefix+p;
let catalogue,snapshot,config,session='',rankData,selectedBoard,page=1,rankSelected=0,epoch=0,guildData,matchSelected,personSelected,boundNumber='';
const finite=v=>typeof v==='number'&&Number.isFinite(v),fmt=v=>finite(v)?new Intl.NumberFormat('en',{maximumFractionDigits:0}).format(v):'—';
const date=v=>finite(v)?new Date(v*1000).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'Date unavailable';
function completionTime(row,mode){const ts=mode==='no_hit'?Math.abs(Array.isArray(row.score)?row.score[0]:row.score):row.ud?.ts;return finite(ts)&&ts>=946684800&&ts<4102444800?new Date(ts*1000).toLocaleString(undefined,{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',timeZoneName:'short'}):'Completion time not reported';}
function score(v,mode){v=Array.isArray(v)?v[0]:v;if(!finite(v)||!v)return '—';if(mode==='no_hit')return new Date(Math.abs(v)*1000).toISOString().slice(0,10)+' UTC';v=Math.abs(v);return `${Math.floor(v/60)}:${(v%60).toFixed(3).padStart(6,'0')}`;}
async function api(path,options={}){const response=await fetch(url(path),{...options,headers:{...(session?{Authorization:'Bearer '+session}:{}),...options.headers}});if(!response.ok){let body;try{body=await response.json();}catch{}throw Error(body?.error||'Request failed. Please try again.');}return response.json();}
function empty(text){return `<div class="empty">${esc(text)}</div>`;}
function rankPlayer(pid,row){return rankData?.player_names?.[pid]?.name||row.player_info?.[pid]?.base?.nickname||((pid===row.pid||pid===row.ud?.leader_id)?row.player_info?.base?.nickname:null)||snapshot?.players?.[pid]?.name||'Name unavailable';}
async function hydrateMatch(){const data=guildData,index=matchSelected,m=data?.matches?.[index];if(!m||config.mode==='preview'||m._activityNamesLoaded)return;try{const resolved=await api('/api/guild?number='+encodeURIComponent(data.searchNumber)+'&match='+encodeURIComponent(m.id));if(guildData!==data)return;data.matches[index]={...resolved,_activityNamesLoaded:true};if(matchSelected===index)renderGuild();}catch(e){if(guildData===data&&matchSelected===index)$('guild-state').textContent+=' Player names could not be loaded; you can select this match again to retry.';}}
function names(kind,values){return values?.length?values.map(v=>`<span class="skill">${esc(v===0?'Empty':catalogue.names[kind]?.[v]||`ID ${v}`)}</span>`).join(''):'Not recorded';}
function boardList(){const family=$('family').value,term=$('search').value.trim().toLowerCase();const list=catalogue.boards.filter(b=>b.family===family&&(!term||`${b.title} ${b.key}`.toLowerCase().includes(term)));$('board').innerHTML=list.map(b=>`<option value="${esc(b.key)}">${esc(b.title)}</option>`).join('');$('mode-label').hidden=family!=='abyss';page=1;loadRank();}
function rankName(entry){if(entry.family!=='abyss')return entry.rank_name;const mode=$('mode').value;if(mode==='path'){if(entry.special_no_path_ui)throw Error('This encounter uses special rules; the game hides its normal Path Trial. Choose another mode.');if(entry.paths?.length!==1||!entry.paths[0].name)throw Error('No single named Path Trial was extracted for this boss.');return entry.paths[0].rank_name;}return mode==='no_hit'?entry.no_hit_rank_name:entry.overall_rank_name;}
async function loadRank(){const ticket=++epoch;selectedBoard=catalogue.boards.find(b=>b.key===$('board').value);rankSelected=0;rankData=null;$('rank-detail').innerHTML=empty('Select a ranked entry to inspect its recorded data.');$('prev').disabled=$('next').disabled=true;$('rank-count').textContent='';$('page-label').textContent='';
 if(!selectedBoard){$('board-title').textContent='No matching encounters';$('hero').style.backgroundImage='none';$('board-description').textContent='Try another name or category.';$('board-tags').textContent='';$('board-family').textContent='SEARCH';$('rank-list').innerHTML=empty('No matching encounters.');return;}
 const b=selectedBoard,mode=b.family==='abyss'?$('mode').value:'overall';$('hero').style.backgroundImage=b.image?`url("${url(b.image)}")`:'none';$('board-family').textContent={abyss:'ABYSS TRIAL',hr:'HERO’S REALM',st:'SWORD TRIAL'}[b.family];$('board-title').textContent=b.title;
 $('board-description').textContent=mode==='path'?(b.paths?.[0]?.name||'Path Trial'):mode==='no_hit'?'No-hit completions, displayed as dates.':'Ranked clear times. Select a result to look closer.';
 $('board-tags').innerHTML=`<span class="tag">${mode==='path'?'PATH TRIAL':mode==='no_hit'?'NO-HIT DATES':'FASTEST CLEARS'}</span><span class="tag">${config.mode==='preview'?'SAVED SNAPSHOT':'LIVE API · CACHED 3 MIN'}</span>`;
 $('detail-heading').textContent=b.family==='abyss'?'Recorded build':'Recorded team';$('rank-list').innerHTML=empty('Loading records…');
 try{const name=rankName(b);const result=config.mode==='preview'?snapshot.ranks[name]:await api(`/api/rank?board=${encodeURIComponent(b.key)}&mode=${mode}&page=${page}`);if(ticket!==epoch)return;rankData=result;renderRanks();}
 catch(e){if(ticket===epoch){$('rank-list').innerHTML=empty(e.message);$('rank-detail').innerHTML=empty('No run selected.');}}
}
function renderRanks(){const rows=rankData?.rank_list||[],mode=selectedBoard.family==='abyss'?$('mode').value:'overall';$('rank-count').textContent=`${rows.length} shown · ${fmt(rankData?.rank_total_len)} ranked`;$('page-label').textContent=config.mode==='preview'?'Snapshot sample':`Page ${page}`;$('prev').disabled=config.mode==='preview'||page<=1;$('next').disabled=config.mode==='preview'||page*20>=(rankData?.rank_total_len||0);
 if(!rows.length){$('rank-list').innerHTML=empty(config.mode==='preview'?'This encounter has no saved sample. Its original artwork and definition are available; live rankings require Discord configuration.':'No ranked entries returned. The board may be empty or unavailable in this region.');return;}
 $('rank-list').innerHTML=rows.map((r,i)=>`<button class="rank-row ${i===rankSelected?'active':''}" data-rank="${i}"><span class="rank-no">${(page-1)*20+i+1}</span><span class="grow">${esc(rankPlayer(r.ud?.leader_id||r.pid,r))}<small>${selectedBoard.family==='abyss'?completionTime(r,mode):`${r.ud?.members?.length??'—'} team members · ${completionTime(r,mode)}`}</small></span><span class="result">${esc(score(r.score,mode))}</span></button>`).join('');$('rank-list').querySelectorAll('[data-rank]').forEach(el=>el.onclick=()=>{rankSelected=Number(el.dataset.rank);renderRanks();});renderBuild(rows[rankSelected],mode);}
function renderBuild(row,mode){const ud=row.ud||{},skills=ud.battle_skills;let body=`<h2>${esc(rankPlayer(ud.leader_id||row.pid,row))}</h2><p class="result">${esc(score(row.score,mode))}</p>`;
 if(selectedBoard.family==='abyss'){body+=`<p class="subnote">${esc(completionTime(row,mode))}</p>`;body+=Array.isArray(skills)?[['Martial arts','martial',skills.slice(0,2)],['Inner Ways','inner',skills.slice(3,7)],['Mystic Skills','mystic',skills.slice(7)]].map(([title,kind,values])=>`<div class="detail-group"><h4>${title.toUpperCase()}</h4>${names(kind,values)}</div>`).join(''):empty('Build was not recorded.');}
 else {body+=`<div class="detail-group"><h4>TEAM ROSTER</h4>${(ud.members||[]).map(pid=>{const p=typeof pid==='string'?pid:pid.pid;return `<div class="skill">${esc(rankPlayer(p,row))}${p===ud.leader_id?' · Leader':''}</div>`;}).join('')||'Not recorded'}</div><p class="subnote">Recorded ${esc(date(ud.ts))}. ${(ud.spaceids||[]).length} run-associated space IDs; no historical damage report is available.</p>`;}
 if(ud.device_name)body+=`<p class="subnote">Platform: ${esc(ud.device_name)}</p>`;body+='<p class="subnote">Skills reflect the recorded result, not current equipment. Unknown IDs and empty slots remain visible.</p>';$('rank-detail').innerHTML=`<div class="detail-content">${body}</div>`;}
function populateGuild(){const matches=guildData?.matches||[];$('match').innerHTML=matches.map((m,i)=>`<option value="${i}">${esc(date(m.timestamp))} · ${esc(m.outcome)} · Round ${esc(m.round??'—')}</option>`).join('');matchSelected=Math.max(0,matches.findIndex(m=>finite(m.stats?.total_damage)&&new Set(Object.values(m.participants||{}).map(s=>s.camp)).size>1));$('match').value=String(matchSelected);
 $('guild-state').className='status';$('guild-state').textContent=matches.length?`${matches.length} returned matches contain this player · ${guildData.scanned??'—'} guild reports checked. Current guild only; not lifetime or Arena history.${guildData.partial?' Some records were unavailable.':''}`:({no_guild:'This player is not currently in a guild.',no_records:'No battle IDs were returned for the current guild.',unavailable:'The game service did not return usable guild data.'}[guildData?.status]||'No returned guild report contains this player. They may not have participated, or older records may be unavailable.');renderGuild();}
function metric(label,value){return `<div class="metric"><small>${esc(label)}</small><strong>${esc(value)}</strong></div>`;}
function participantName(m,pid){return m.player_names?.[pid]?.name||snapshot?.players?.[pid]?.name||'Name unavailable';}
function renderGuild(){const m=guildData?.matches?.[matchSelected];if(!m){$('guild-summary').innerHTML='';$('red-team').innerHTML=$('blue-team').innerHTML=empty('No match selected.');$('participant-detail').innerHTML=empty('No participant selected.');$('red-name').textContent=$('blue-name').textContent='';return;}
 const own=m.stats||{};$('guild-summary').innerHTML=metric('PLAYER RESULT',m.outcome)+metric('PLAYER DAMAGE',fmt(own.total_damage))+metric('PLAYER HEALING',fmt(own.healing_done))+metric('K / D / A',`${fmt(own.kills)} / ${fmt(own.deaths)} / ${fmt(own.assists)}`);
 for(const [side,camp] of [['red',1],['blue',2]]){const club=m.guilds?.[side==='red'?'Red':'Blue'];$(side+'-name').textContent=guildData.names?.[club]||club||'Guild unavailable';const participants=Object.entries(m.participants||{}).filter(([,s])=>s.camp===camp).sort((a,b)=>(b[1].total_damage??-1)-(a[1].total_damage??-1));
 $(side+'-team').innerHTML=`<div class="team-table"><table><thead><tr><th>PLAYER</th><th>DAMAGE</th><th>HEALING</th><th>K / D / A</th></tr></thead><tbody>${participants.map(([pid,s])=>`<tr data-pid="${esc(pid)}" tabindex="0"><td>${esc(participantName(m,pid))}${pid===m.player_pid?'<small>SEARCHED PLAYER</small>':''}</td><td>${fmt(s.total_damage)}</td><td>${fmt(s.healing_done)}</td><td>${fmt(s.kills)} / ${fmt(s.deaths)} / ${fmt(s.assists)}</td></tr>`).join('')}</tbody></table></div>`;}
 document.querySelectorAll('[data-pid]').forEach(el=>{el.onclick=()=>showParticipant(el.dataset.pid);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showParticipant(el.dataset.pid);}};});showParticipant(m.player_pid);}
function showParticipant(pid){personSelected=pid;const m=guildData.matches[matchSelected],s=m.participants[pid]||{};document.querySelectorAll('[data-pid]').forEach(el=>el.classList.toggle('selected',el.dataset.pid===pid));const all=Object.values(m.participants),max=Math.max(1,...all.map(x=>finite(x.total_damage)?x.total_damage:0));
 $('participant-detail').innerHTML=`<div class="detail-content"><h2>${esc(participantName(m,pid))}</h2><p>${s.camp===1?'Red team':s.camp===2?'Blue team':'Camp unavailable'}</p><div class="metrics">${[['Damage dealt',s.total_damage],['Damage taken',s.damage_taken],['Healing',s.healing_done],['Objectives · wall damage',s.damage_wall],['Kills',s.kills],['Deaths',s.deaths],['Assists',s.assists],['Objectives · goose damage',s.damage_goose]].map(([label,value])=>metric(label,fmt(value))).join('')}</div><div class="detail-group"><h4>DAMAGE COMPARED WITH THIS MATCH’S TOP PLAYER</h4>${finite(s.total_damage)?`<div class="bar"><span style="width:${Math.max(0,Math.min(100,s.total_damage/max*100))}%"></span></div>`:'Not reported'}</div><p class="subnote">A dash means the report did not include that metric. Objective damage is shown separately; it is not added to total damage. Resolved player names may differ from their names at match time.</p></div>`;}
async function searchGuild(){if(config.mode==='preview')return;$('guild-search').disabled=true;$('guild-state').textContent='Finding the player’s current guild and participant reports…';try{const number=$('player-number').value.trim();guildData=await api('/api/guild?number='+encodeURIComponent(number));guildData.searchNumber=number;populateGuild();hydrateMatch();}catch(e){guildData={matches:[]};populateGuild();$('guild-state').className='error';$('guild-state').textContent=e.message;}finally{$('guild-search').disabled=false;}}
function showTab(tab){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));for(const section of ['rankings','guild','players'])$(section).hidden=section!==tab;$('breadcrumb').textContent={rankings:'Rankings',guild:'Guild battles',players:'Players'}[tab];}
let profileEpoch=0;
let profileTarget='',profileSections={},collectionFilter='';
function renderProfile(p){profileTarget=p.number||$('profile-query').value.trim();profileSections={};const guild=p.guild?.status==='none'?'No current guild':p.guild?.status==='joined'?(p.guild.name||'Guild name unavailable'):'Guild membership not reported';
 $('profile-content').innerHTML=`<article class="panel"><div class="detail-content"><div class="eyebrow">PLAYER PROFILE</div><h2>${esc(p.name)}</h2><p>${esc(p.number||'Number ID not reported')}${p.stage_name?' · '+esc(p.stage_name):''}</p>${p.signature?`<p class="profile-signature">${esc(p.signature)}</p>`:''}<div class="metrics">${metric('LEVEL',fmt(p.level))+metric('STATUS',p.status)+metric('SECT',p.sect||'Not reported')+metric('REGION',p.region||'Not reported')}</div><div class="metrics">${metric('ONLINE HOURS',finite(p.online_hours)?String(p.online_hours):'Not reported')+metric('ACCOUNT CREATED',p.created>0?date(p.created):'Not reported')+metric('CURRENT GUILD',guild)}</div><div class="detail-group"><h4>ACHIEVEMENTS BY DIFFICULTY</h4><div class="metrics">${Object.entries(p.achievements||{}).map(([label,value])=>metric(label.toUpperCase(),fmt(value))).join('')}</div></div><button id="profile-battles" class="primary" ${!/^\d{10}$/.test(p.number||'')||p.guild?.status==='none'?'disabled':''}>View this player’s guild battles</button><p class="subnote">Missing values mean the game did not report them. Invisible status takes precedence over online status. Profile fetched ${esc(new Date(p.fetched_at*1000).toLocaleString())}. Guild battles cover returned current-guild records; they are not Arena history.</p></div></article>`;
 const main=$('profile-content').firstElementChild;main.classList.add('profile-main');main.querySelector('.detail-content').insertAdjacentHTML('beforeend',['Martial arts & sect','Fashion & social'].filter(title=>p.details?.[title]).map(title=>`<div class="detail-group"><h3>${esc(title)}</h3>${profileRows(p.details[title])}</div>`).join(''));
 const side=document.createElement('div');side.className='profile-sidebar';side.innerHTML=Object.entries(p.details||{}).filter(([title])=>!['Martial arts & sect','Fashion & social'].includes(title)).map(([title,rows])=>`<article class="panel profile-group"><div class="panel-head"><h3>${esc(title)}</h3></div><div class="detail-content">${profileRows(rows)}</div></article>`).join('');
 const overview=document.createElement('div');overview.className='profile-overview';main.replaceWith(overview);overview.append(main,side);
 $('profile-content').insertAdjacentHTML('beforeend',`${['equipment','collections','social','homestead'].map(section=>`<article class="panel profile-extra" id="profile-${section}"><div class="panel-head"><h3>${esc(section[0].toUpperCase()+section.slice(1))}</h3></div><div id="profile-${section}-state" role="status" class="status">Loading ${section}…</div><div id="profile-${section}-body" class="detail-content"></div></article>`).join('')}`);for(const section of ['equipment','collections','social','homestead'])loadProfileSection(section);

 $('profile-battles').onclick=()=>{$('player-number').value=p.number;showTab('guild');searchGuild();};}
function profileRows(rows){return `<div class="profile-data-grid">${rows.map(r=>metric(r.label,r.value===null||r.value===undefined||r.value===''?'Not reported':typeof r.value==='number'?new Intl.NumberFormat('en',{maximumFractionDigits:3}).format(r.value):r.value)).join('')}</div>`;}
function collectionRows(data){const labels={fashion:'Poses & collectibles',guise:'Outfits & skins',titles:'Titles · level',ride:'Mounts · count or level'};const all=Object.entries(data.buckets||{}).flatMap(([category,rows])=>rows.map(r=>({...r,category})));const filtered=all.filter(r=>(labels[r.category]+' '+r.name).toLowerCase().includes(collectionFilter.toLowerCase()));$('collection-list').innerHTML=filtered.length?`<table><thead><tr><th>Name</th><th>Category</th><th>Count / level</th></tr></thead><tbody>${filtered.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(labels[r.category])}</td><td>${esc(r.value??'—')}</td></tr>`).join('')}</tbody></table>`:empty('No returned collection entries match this filter.');$('collection-page').textContent=`${filtered.length} of ${all.length} returned entries`;}
function renderProfileSection(data){const body=$('profile-'+data.section+'-body');if(data.section==='equipment'){
 const groups=['Offensive','Defensive','Ring & bow','Other'];
 body.innerHTML='<p class="subnote">Bars show value ÷ the extracted affix maximum. Relay labels show the game’s tier-specific transfer limit. Unknown references remain unavailable.</p>'+groups.map(group=>{const items=(data.items||[]).filter(item=>(item.group||'Other')===group);return items.length?`<section class="gear-section"><h3>${esc(group)}</h3><div class="gear-grid ${group==='Ring & bow'?'gear-grid-pair':''}">${items.map(item=>`<article class="gear-card" data-quality="${esc(item.quality)}"><header><div class="eyebrow">${esc(item.slot)}</div><h3>${esc(item.name)}</h3><span class="gear-count">${item.affixes?.length||0} affixes</span></header>${profileRows([{label:'Tier',value:item.tier},{label:'Quality',value:item.quality},{label:'Set',value:item.set},{label:'Relay',value:item.relayed?'Relayed':'Not relayed'},...(item.attributes||[])])}${item.relayed&&finite(item.relay_limit_percent)?`<p class="relay-note">Relay transfer limit · ${esc(item.relay_limit_percent)}% of max</p>`:''}<h4>AFFIX ROLLS</h4>${item.affixes?.length?item.affixes.map(a=>`<div class="gear-affix"><div class="gear-affix-heading"><span>${esc(a.name)}</span><strong>${esc(a.display??a.value??'Not reported')}</strong></div>${finite(a.roll_percent)?`<div class="roll-track" role="meter" aria-label="${esc(a.name)} percent of maximum" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${a.roll_percent}"><span style="width:${Math.max(0,Math.min(100,a.roll_percent))}%"></span></div><div class="roll-caption"><span>Reference ${esc(a.minimum_display??a.minimum)} – ${esc(a.maximum_display??a.maximum)}</span><span>${esc(a.roll_percent)}% of max</span></div>`:`<p class="subnote">${esc(a.range_status||'Range unavailable')}${a.minimum!=null&&a.maximum!=null?' · '+esc(a.minimum_display??a.minimum)+' – '+esc(a.maximum_display??a.maximum):''}</p>`}</div>`).join(''):empty('No affixes returned for this slot.')}</article>`).join('')}</div></section>`:'';}).join('')||empty('No equipped items were returned.');}

 else if(data.section==='collections'){body.innerHTML='<label>Filter collected items<input id="collection-filter" placeholder="Name or category…"></label><div id="collection-list" class="profile-table"></div><div class="pagination"><span id="collection-page"></span></div><p class="subnote">Names use category-specific extracted mappings. Titles show level; other categories show the returned count or level. Unmapped or ambiguous IDs remain explicitly labelled.</p>';collectionFilter='';$('collection-filter').oninput=()=>{collectionFilter=$('collection-filter').value;collectionRows(data);};collectionRows(data);}
 else if(data.section==='social'){body.innerHTML=profileRows([{label:'Returned topic likes',value:data.likes}])+`<h4>Partners</h4>${data.partners?.length?data.partners.map(p=>`<div class="profile-affix"><strong>${esc(p.name)}</strong><p>${esc(p.number||'Number ID not reported')} · Favor ${esc(p.favor??'not reported')}</p></div>`).join(''):empty('No partner references were returned.')}<p class="subnote">${data.partial?'Some social lookups were unavailable. ':' '}Names are resolved using each partner’s recorded server.</p>`;}
 else body.innerHTML=data.rows?.length?profileRows(data.rows):empty(data.message||'No homestead data returned.');}
async function loadProfileSection(section){const target=profileTarget,epoch=profileEpoch;try{const data=await api('/api/player?identifier='+encodeURIComponent(target)+'&section='+section);if(epoch!==profileEpoch)return;profileSections[section]=data;renderProfileSection(data);$('profile-'+section+'-state').textContent='Loaded for this player.';}catch(e){if(epoch===profileEpoch){$('profile-'+section+'-state').className='error';$('profile-'+section+'-state').textContent=e.message+' Search again to refresh. Other sections remain available.';}}}
async function searchProfile(){if(config.mode==='preview')return;const request=++profileEpoch;$('profile-search').disabled=true;$('profile-state').className='status';$('profile-state').textContent='Finding player and loading their profile…';$('profile-content').innerHTML='';try{const p=await api('/api/player?identifier='+encodeURIComponent($('profile-query').value.trim()));if(request!==profileEpoch)return;renderProfile(p);$('profile-state').textContent='Current data returned by the game service.';}catch(e){if(request===profileEpoch){$('profile-state').className='error';$('profile-state').textContent=e.message;}}finally{if(request===profileEpoch)$('profile-search').disabled=false;}}
async function start(){try{config=await api('/api/config');catalogue=await api('/catalogue.json');
 if(embedded){if(config.mode!=='discord'||!config.client_id)throw Error('This is a local preview server. Configure Discord mode before embedding it.');const {DiscordSDK}=await import('./discord-sdk.js');const sdk=new DiscordSDK(config.client_id);await sdk.ready();const {code}=await sdk.commands.authorize({client_id:config.client_id,response_type:'code',state:crypto.randomUUID(),prompt:'none',scope:['identify']});const auth=await api('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});session=auth.session;boundNumber=auth.user.character_number||'';await sdk.commands.authenticate({access_token:auth.access_token});$('identity').textContent=auth.user.name+(auth.user.bound?' · Character bound':' · Character not bound');$('notice').textContent='Connected through Discord. Guild searches require your own current character binding.';$('connection').textContent='Discord connected';guildData={matches:[]};}
 else {if(config.mode!=='preview')throw Error('Open this application through Discord to authenticate.');snapshot=await api('/api/snapshot');guildData=snapshot.guild;$('notice').textContent=`LOCAL PREVIEW · Saved public data from ${snapshot.captured}. No live connection, Discord login or messages.`;$('connection').textContent='Snapshot preview';$('player-number').placeholder='Sample player · '+(snapshot.players[snapshot.own]?.name||'Public sample');$('player-number').disabled=true;$('guild-search').disabled=true;}
 document.querySelectorAll('[data-tab]').forEach(el=>el.onclick=()=>showTab(el.dataset.tab));$('family').onchange=boardList;$('search').oninput=boardList;$('board').onchange=()=>{page=1;loadRank();};$('mode').onchange=()=>{page=1;loadRank();};$('prev').onclick=()=>{page--;loadRank();};$('next').onclick=()=>{page++;loadRank();};$('match').onchange=()=>{matchSelected=Number($('match').value);renderGuild();hydrateMatch();};$('guild-search').onclick=searchGuild;
 $('profile-form').onsubmit=e=>{e.preventDefault();searchProfile();};$('profile-own').disabled=!boundNumber;$('profile-own').onclick=()=>{$('profile-query').value=boundNumber;searchProfile();};$('profile-query').value=boundNumber;if(config.mode==='preview'){$('profile-query').disabled=true;$('profile-search').disabled=true;$('profile-state').textContent='Player search requires Discord authentication; this saved preview has no live player lookup.';}else if(boundNumber){$('profile-state').textContent='Your bound character is filled in. Search it, or enter another player’s Number ID or exact nickname.';} boardList();$('board').value='abyss:3';loadRank();populateGuild();if(boundNumber){$('player-number').value=boundNumber;searchGuild();}
 }catch(e){$('notice').className='error';$('notice').textContent=e.message;$('connection').textContent='Connection unavailable';}}
start();
